"""Add reviewee_id to review table

Revision ID: afdeb54a5032
Revises: d984615bbd89
Create Date: 2021-03-08 15:05:25.707151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdeb54a5032'
down_revision = 'd984615bbd89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reviewee_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'reviewee_id')
    # ### end Alembic commands ###
