"""Add response_id to review

Revision ID: d984615bbd89
Revises: c3bde6113cb6
Create Date: 2021-03-05 15:34:53.604346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd984615bbd89'
down_revision = 'c3bde6113cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('response_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'response_id')
    # ### end Alembic commands ###
