"""empty message

Revision ID: 86c3d8188292
Revises: afdeb54a5032
Create Date: 2021-03-23 15:49:45.114261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c3d8188292'
down_revision = 'afdeb54a5032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nonprofit_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('karma_per_share', sa.Integer(), nullable=False),
    sa.Column('cost_per_share', sa.Float(), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=35), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nonprofit_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
