"""empty message

Revision ID: a00e00859787
Revises: a3b5691888a9
Create Date: 2021-03-25 11:47:58.571377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00e00859787'
down_revision = 'a3b5691888a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('millikarma_per_share', sa.Integer(), nullable=False))
    op.drop_column('projects', 'karma_per_share')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('karma_per_share', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('projects', 'millikarma_per_share')
    # ### end Alembic commands ###
